sudo: false
language: node_js
node_js:
  - 7.7

branches:
  only:
  - master
  - develop

env:
  NODE_ENV: test
git:
  depth: 3

install:
  - yarn

script:
  - yarn test:ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  yarn: true
  directories:
    - node_modules
