// flow-typed signature: 5c2f164112001608245c11f4487eed26
// flow-typed version: <<STUB>>/babel-preset-boldr_v^0.7.10/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-boldr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-boldr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-boldr/client' {
  declare module.exports: any;
}

declare module 'babel-preset-boldr/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-boldr/client.js' {
  declare module.exports: $Exports<'babel-preset-boldr/client'>;
}
declare module 'babel-preset-boldr/index' {
  declare module.exports: $Exports<'babel-preset-boldr'>;
}
declare module 'babel-preset-boldr/index.js' {
  declare module.exports: $Exports<'babel-preset-boldr'>;
}
declare module 'babel-preset-boldr/server.js' {
  declare module.exports: $Exports<'babel-preset-boldr/server'>;
}
