// flow-typed signature: 7f4f270d82a7485e444cb475454eefa1
// flow-typed version: <<STUB>>/coolors-to-hex_v^1.0.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coolors-to-hex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'coolors-to-hex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'coolors-to-hex/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'coolors-to-hex/dist/index.js' {
  declare module.exports: $Exports<'coolors-to-hex/dist/index'>;
}
declare module 'coolors-to-hex/index' {
  declare module.exports: $Exports<'coolors-to-hex'>;
}
declare module 'coolors-to-hex/index.js' {
  declare module.exports: $Exports<'coolors-to-hex'>;
}
