// flow-typed signature: 97db69a4543aaa9fe63edf0fbe49e9c2
// flow-typed version: <<STUB>>/cz-conventional-kawaii_v^0.1.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cz-conventional-kawaii'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cz-conventional-kawaii' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cz-conventional-kawaii/index' {
  declare module.exports: $Exports<'cz-conventional-kawaii'>;
}
declare module 'cz-conventional-kawaii/index.js' {
  declare module.exports: $Exports<'cz-conventional-kawaii'>;
}
