// flow-typed signature: 883f5c51a066890ac4a2fecce080b41b
// flow-typed version: <<STUB>>/draftjs-to-html_v^0.7.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draftjs-to-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'draftjs-to-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draftjs-to-html/lib/draftjs-to-html' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draftjs-to-html/lib/draftjs-to-html.js' {
  declare module.exports: $Exports<'draftjs-to-html/lib/draftjs-to-html'>;
}
