// flow-typed signature: e18b4f8d81b4dbdb35600e7f704af999
// flow-typed version: <<STUB>>/html-looks-like_v^1.0.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-looks-like'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-looks-like' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-looks-like/lib/diff' {
  declare module.exports: any;
}

declare module 'html-looks-like/lib/index' {
  declare module.exports: any;
}

declare module 'html-looks-like/lib/report' {
  declare module.exports: any;
}

declare module 'html-looks-like/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-looks-like/lib/diff.js' {
  declare module.exports: $Exports<'html-looks-like/lib/diff'>;
}
declare module 'html-looks-like/lib/index.js' {
  declare module.exports: $Exports<'html-looks-like/lib/index'>;
}
declare module 'html-looks-like/lib/report.js' {
  declare module.exports: $Exports<'html-looks-like/lib/report'>;
}
declare module 'html-looks-like/lib/types.js' {
  declare module.exports: $Exports<'html-looks-like/lib/types'>;
}
