// flow-typed signature: 590713e106f2353de61c6e4c621f5b79
// flow-typed version: <<STUB>>/lodash.partial_v^4.2.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.partial'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.partial' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'lodash.partial/index' {
  declare module.exports: $Exports<'lodash.partial'>;
}
declare module 'lodash.partial/index.js' {
  declare module.exports: $Exports<'lodash.partial'>;
}
