// flow-typed signature: b7db627de56b7de365ecf4c1ac7fce3e
// flow-typed version: <<STUB>>/lodash.take_v^4.1.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.take'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.take' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'lodash.take/index' {
  declare module.exports: $Exports<'lodash.take'>;
}
declare module 'lodash.take/index.js' {
  declare module.exports: $Exports<'lodash.take'>;
}
