// flow-typed signature: b9faafba9cc54e6eb26b2eb7d71123ec
// flow-typed version: <<STUB>>/lodash.trim_v^4.5.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.trim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.trim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'lodash.trim/index' {
  declare module.exports: $Exports<'lodash.trim'>;
}
declare module 'lodash.trim/index.js' {
  declare module.exports: $Exports<'lodash.trim'>;
}
