// flow-typed signature: 48c79b76702d1b9ef5fedd25dd4be732
// flow-typed version: <<STUB>>/normalize.css_v^6.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
