// flow-typed signature: e227523c1798f9c20041eb8bb42e6fe3
// flow-typed version: <<STUB>>/styled-tools_v^0.1.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-tools/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-tools/dist/index.js' {
  declare module.exports: $Exports<'styled-tools/dist/index'>;
}
declare module 'styled-tools/index' {
  declare module.exports: $Exports<'styled-tools'>;
}
declare module 'styled-tools/index.js' {
  declare module.exports: $Exports<'styled-tools'>;
}
