// flow-typed signature: 8a0c5292bb75bbec75bca10f6a43f83b
// flow-typed version: <<STUB>>/@storybook/addon-centered_v^3.2.7/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-centered'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-centered' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-centered/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/vue' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/example/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/src/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/src/vue' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-centered/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/index'>;
}
declare module '@storybook/addon-centered/dist/react.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/react'>;
}
declare module '@storybook/addon-centered/dist/vue.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/vue'>;
}
declare module '@storybook/addon-centered/example/index.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/example/index'>;
}
declare module '@storybook/addon-centered/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/src/index'>;
}
declare module '@storybook/addon-centered/src/react.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/src/react'>;
}
declare module '@storybook/addon-centered/src/vue.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/src/vue'>;
}
